# Generated by Django 4.0.6 on 2022-11-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('children', models.BooleanField()),
                ('extrarequest', models.BooleanField(default=None)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.room')),
            ],
        ),
    ]
