# Generated by Django 4.0.6 on 2022-11-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='extrarequest',
            field=models.BooleanField(default=False),
        ),
    ]
