# Generated by Django 4.0.6 on 2022-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='children',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='extra_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='number_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
