# Generated by Django 4.0.6 on 2022-11-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_reservations_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
