# Generated by Django 4.0.6 on 2022-11-19 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0012_delete_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('children', models.BooleanField(blank=True, default=False, null=True)),
                ('number_of_people', models.IntegerField(blank=True, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('extra_request', models.TextField(blank=True, null=True)),
                ('date_booked', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
