# Generated by Django 4.0.6 on 2023-01-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_room_availability_room_beds_room_capacity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
