# Generated by Django 4.0.6 on 2023-01-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_room_price_alter_reservation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
    ]
