# Generated by Django 4.0.6 on 2023-01-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
