# Generated by Django 4.0.6 on 2023-01-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_room_identity_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='identity_number',
        ),
    ]
