# Generated by Django 4.0.6 on 2023-01-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_room_identity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtac',
            name='category_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
